- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_password.stdout }}
  with_items:
    - "{{ ansible_hostname }}"
    - 192.168.1.105
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template: src=my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
