---
- name: install php cli
  apt: pkg=php5.6-cli state=latest
  notify:
    - nginx-restart
    - php-fpm-restart

- name: configure php cli
  template: src=php.ini.j2 dest=/etc/php/5.6/cli/php.ini
  notify:
    - nginx-restart
    - php-fpm-restart
