---
ssl_certs_country: "AU"
ssl_certs_locality: "Australia"
ssl_certs_organization: "Webdawe"
ssl_certs_state: "Melbourne"
ssl_certs_common_name: "*.webdawe.dev"
ssl_certs_days: "365"
ssl_certs_fields: "/C={{ssl_certs_country}}/ST={{ssl_certs_state}}/L={{ssl_certs_locality}}/O={{ssl_certs_organization}}/CN={{ssl_certs_common_name}}"

ssl_certs_path: "/etc/ssl/{{ssl_certs_common_name}}"
ssl_certs_path_owner: "www-data"
ssl_certs_path_group: "www-data"
ssl_certs_privkey_path: "{{ssl_certs_path}}/webdawe.dev.key"
ssl_certs_cert_path: "{{ssl_certs_path}}/webdawe.dev.pem"
ssl_certs_csr_path: "{{ssl_certs_path}}/webdawe.dev.csr"
ssl_certs_dhparam_path: "{{ssl_certs_path}}/dhparam.pem"
ssl_certs_mode: "0700"

ssl_certs_local_privkey_path: "{{inventory_dir|default(playbook_dir)}}/files/ssl/webdawe.dev.key"
ssl_certs_local_cert_path: "{{inventory_dir|default(playbook_dir)}}/files/ssl/webdawe.dev.pem"

ssl_certs_generate_self_signed: true
ssl_certs_key_size: "2048"
ssl_certs_generate_dh_param: false
ssl_certs_dhparam_size: "2048"
